### ISSUE TITLE
[Bug] Possible Incomplete or Missing Content

### ISSUE THREAD

**Issue by 0xsha1man** [0xsequence/niftyswap-feedback#6]
# Possible Incomplete or Missing Content

## About Page (https://test.niftyswap.io/about)
<img align="left" width="100%" src="https://user-images.githubusercontent.com/104043928/166140418-adac49db-478c-4118-b9b6-6cced478e27e.png" />

- **Currency** link takes you to: https://github.com/0xsequence/niftyswap#currency
    - The anchor tag isn't listed on the resulting readme.md and thus you're presented at the very top of the GitHub page. Nowhere is the word Currency used in a heading or subheading furthering the confusion.
- The **Specification.pdf** link takes you to: https://github.com/0xsequence/niftyswap/blob/master/SPECIFICATIONS.md
    - This is not a pdf as the link describes. 

## Feature Your Collection (full link below in description)
<img align="left" width="30%" src="https://user-images.githubusercontent.com/104043928/166140674-ac637c8b-70e4-4b22-ac96-ff2e5a23ee7b.png" />

Clicking on the call-to-action from the landing page takes you to: https://github.com/0xsequence/niftyswap-directory/issues/new?assignees=&labels=new+collection+request&template=new_collection_request.yaml&title=New+Collection+Request

The resulting page on GitHub, [*Issue: New Collection Request*](https://github.com/0xsequence/niftyswap-directory/issues/new?assignees=&labels=new+collection+request&template=new_collection_request.yaml&title=New+Collection+Request), there is a link labeled "[choose a different type](https://github.com/0xsequence/niftyswap-directory/issues/new/choose)" below the title.

- Link takes you to a list of issue templates and there is only the 1 template you just navigated away from, the phrase "choose a different type" implies there were other types
- There is a blank issue template but this is outside of the workflow the user was actively within.

**Comment by scotato** [comment]
we will get these fixed up, thank you!!
